### ISSUE TITLE
Datenbankzugriff mit Peewee 

### ISSUE THREAD

**Issue by Hofei90** [Hofei90/smartmeter#1]
Datenbankzugriff mit Peewee umsetzen, um dem Benutzer die Wahlmöglichkeit zwischen sqlite3, MySQL und Postgres anbieten zu können

**Comment by Hofei90** [comment]
Erledigt - zusätzlich Integration mit PostgREST

**Comment by linusg** [comment]
https://github.com/Hofei90/smartmeter/commit/223018363fa68c46ebb7eebe5f0ab83e73ca302f, https://github.com/Hofei90/smartmeter/commit/1978869aa3c0ad33c9f3e041128cb76231077ba8
