### ISSUE TITLE
Syntax error smartmeter.py line 94

### ISSUE THREAD

**Issue by JimKnopf1503** [Hofei90/smartmeter#10]
Hi!

I get following error:
root@raspberrypi:/home/pi/smartmeter# python3 smartmeter.py
  File "smartmeter.py", line 94
    self.headers = {f"Authorization": "{user} {token}".format(user=CONFIG["db"]["postgrest"]["user"],
                                   ^
SyntaxError: invalid syntax

Burkhard

**Comment by Hofei90** [comment]
Hallo,
welche Pythonversion hast du im Einsatz?
Wie sieht deine Konfigurationsdatei aus?

--------------------------

Hello,
what version of python are you running?
What does your configuration file look like?

**Comment by JimKnopf1503** [comment]
Hi!
Nachdem ich auch noch Probleme mit dem mysql connector hatte habe ich mein System nochmal komplett neu aufgesetzt.
Muss zugeben, dass ich es danach nicht mehr ausprobiert habe.
Kann von daher wohl geschlossen werden.
Gruß,
Burkhard
