### ISSUE TITLE
DRT428DC-MID

### ISSUE THREAD

**Issue by Hanspi59** [Hofei90/smartmeter#16]
Hallo Hofei90!
Ich habe 3 Stück 3-Phasen Zähler DRT428 von B + G im Einsatz.
Frage: kann ich die Benutzen? Und wie kann ich alle drei in Deinem Projekt einbinden?
Bin nicht so fit im Programmieren.
Kannst Du mir ein paar Tips geben? Wäre sehr dankbar!
Gruss
Hanspi

**Comment by Hofei90** [comment]
Hallo,
dieses Projekt hier bezieht die Daten über die Modbusschnittstelle. Der genannte Stromzähler besitzt keine Modbusschnittstelle sondern einen S0 Ausgang. Du benötigst ein Projekt, welches mit dem S0 Ausgang die Daten abfrägt.
Weitere Hilfe könntest du z.B hier erfragen: https://forum-raspberrypi.de/forum/
