### ISSUE TITLE
TypeError: convert_daten_to_influxformat() missing 1 required positional argument: 'device'

### ISSUE THREAD

**Issue by markusbuecher** [Hofei90/smartmeter#18]
Es wurde von mir ein neues Device eingepflegt. Wenn der Devicename falsch wäre würde es doch schon in der Config der .toml rausfliegen.

Traceback (most recent call last):
  File "smartmeter.py", line 260, in <module>
    main()
  File "smartmeter.py", line 250, in main
    messhandler.schreibe_messwerte(datenbankschnittstelle)
  File "smartmeter.py", line 73, in schreibe_messwerte
    datenbankschnittstelle.insert_many(self.messwerte_liste)
  File "smartmeter.py", line 123, in insert_many
    influx_daten = convert_daten_to_influxformat(daten)
TypeError: convert_daten_to_influxformat() missing 1 required positional argument: 'device'

**Comment by Hofei90** [comment]
Ohne deine Änderungen zu kennen ist es schwer zu sagen was los ist.
